export const wColor = "rgb(255,255,0)"
export const eColor = "rgb(255,0,0)"
export const sColor = "#1afaa8"
export const iColor = "#535c6c"
export const lColor = "rgb(255,255,255)"
export const rColor = "#faa81a"
export const rColor2 = "#e1e1e1"

export const wStyle = `color: ${wColor};`
export const eStyle = `color: ${eColor};`
export const sStyle = `color: ${sColor};`
export const iStyle = `color: ${iColor};`
export const lStyle = `color: ${lColor};`
export const wStyleBold = `color: ${wColor}; font-weight: bold;`
export const eStyleBold = `color: ${eColor}; font-weight: bold;`
export const sStyleBold = `color: ${sColor}; font-weight: bold;`
export const iStyleBold = `color: ${iColor}; font-weight: bold;`
export const lStyleBold = `color: ${lColor}; font-weight: bold;`
export const rStyle = `color: ${rColor}; font-size: 1.1em;`
export const rStyle2 = `color: ${rColor2}; font-size: 1em;`