name: Publish Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install web-ext
      run: npm install --save-dev web-ext

    - name: Sign Extension
      env:
        WEB_EXT_API_KEY: ${{ secrets.WEB_EXT_API_KEY }}
        WEB_EXT_API_SECRET: ${{ secrets.WEB_EXT_API_SECRET }}
      run: npx web-ext sign --source-dir=build --artifacts-dir=build --api-key=$WEB_EXT_API_KEY --api-secret=$WEB_EXT_API_SECRET


    - name: Extract changelog for current version
      id: changelog
      run: |
        TAG_NAME="${GITHUB_REF#refs/tags/}"
        VERSION="${TAG_NAME#v}"
        CHANGELOG=$(awk "/^# Version $VERSION/,/^# Version /{if (!/^# Version $VERSION/) print}" changelog.md | sed '$d')
        echo "::set-output name=changelog::$CHANGELOG"

    - name: Create GitHub Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        TAG_NAME="${GITHUB_REF#refs/tags/}"
        RELEASE_NAME="Release $TAG_NAME"
        CHANGELOG="${{ steps.changelog.outputs.changelog }}"
        gh release create "$TAG_NAME" --title "$RELEASE_NAME" --notes "$CHANGELOG" build/emoji.zip build/emoji-src.zip